/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-variant": "#d3e4fe",
        "surface-dim": "#cbdbf5",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#434654",
        "primary": "#003d9b",
        "primary-container": "#0052cc",
        "primary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001848",
        "on-primary-fixed-variant": "#0040a2",
        "on-primary-container": "#c4d2ff",
        "secondary": "#006c49",
        "secondary-container": "#6cf8bb",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00714d",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        "tertiary": "#444700",
        "tertiary-container": "#5c5f00",
        "tertiary-fixed": "#e5eb07",
        "tertiary-fixed-dim": "#c8ce00",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#d5dc00",
        "on-tertiary-fixed": "#1c1d00",
        "on-tertiary-fixed-variant": "#474a00",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "outline": "#737685",
        "outline-variant": "#c3c6d6",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "inverse-primary": "#b2c5ff",
        "surface-tint": "#0c56d0",
        "background": "#f8f9ff",
        "on-background": "#0b1c30",
      },
      fontFamily: {
        "inter": ["Inter", "sans-serif"],
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
